import MainNavigation from './components/mainnav/MainNavigation'
import './globals.css'

export const metadata = {
  title: 'Wage Calculator 1',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <MainNavigation></MainNavigation>
        <main>
          {children}
        </main>
        <footer className='mt-5 p-5 bg-black text-white text-center bottom-0'>2023</footer>
      </body>
    </html>
  )
}
